import numpy as np

from recognizer import Recognizer


def test_recognize_known_phrase():
    """The recogniser should correctly identify a phrase generated by the synthesiser."""
    recogniser = Recognizer()
    audio, sr = recogniser.synth.generate_r2("hello")
    out = recogniser.recognize(audio, sr)
    assert out == "hello"


def test_recognize_common_word():
    """Common words that are in the lexicon should be recognised."""
    recogniser = Recognizer()
    audio, sr = recogniser.synth.generate_r2("yes")
    out = recogniser.recognize(audio, sr)
    assert out == "yes"


def test_recognize_fallback():
    """Unknown phrases should trigger the spelled‑out fallback."""
    recogniser = Recognizer()
    # Create an audio clip spelling out XYZ
    audio, sr = recogniser.synth.generate_r2("XYZ")
    out = recogniser.recognize(audio, sr)
    assert out == "<spelled: XYZ>"


def test_resample_recognition():
    """Recognizer should handle input at different sampling rates by resampling."""
    recogniser = Recognizer()
    phrase = "hello"
    audio, sr = recogniser.synth.generate_r2(phrase)
    # Downsample to half the rate
    import scipy.signal
    new_len = int(len(audio) * 11025 / sr)
    down = scipy.signal.resample(audio, new_len)
    out = recogniser.recognize(down, 11025)
    assert out == phrase


def test_envelope_shapes():
    """Ensure that the internal envelope functions behave as expected."""
    from synth import R2Synth
    synth = R2Synth()
    # Linear envelope decays from 1 to 0
    env_lin = synth._envelope('linear', 10)
    assert abs(env_lin[0] - 1.0) < 1e-3
    assert abs(env_lin[-1] - 0.0) < 1e-3
    # S‑curve starts and ends at zero and peaks near the middle
    env_s = synth._envelope('s-curve', 11)
    assert abs(env_s[0]) < 1e-3
    assert abs(env_s[-1]) < 1e-3
    assert env_s[5] > 0.9  # roughly middle


def test_server_endpoints():
    """Use FastAPI's TestClient to exercise the API endpoints.

    If ``python-multipart`` is not installed the server cannot be
    imported; in that case the test is skipped.
    """
    try:
        from fastapi.testclient import TestClient
        from server import app
    except Exception as exc:
        import pytest
        pytest.skip(f"server import failed: {exc}")
    client = TestClient(app)
    # Synthesis endpoint
    # Missing API key should return 401
    resp_missing = client.post("/to_r2", json={"phrase": "hello"})
    assert resp_missing.status_code == 401
    # Provide API key header for synthesis
    resp = client.post("/to_r2", json={"phrase": "hello"}, headers={"x-api-key": "secret-key"})
    assert resp.status_code == 200
    assert resp.headers['content-type'] in ("audio/wav", "application/octet-stream")
    audio_bytes = resp.content
    files = {'file': ('hello.wav', audio_bytes, 'audio/wav')}
    # Missing API key on recognition should yield 401
    resp2_missing = client.post("/from_r2", files=files)
    assert resp2_missing.status_code == 401
    # Proper call with API key
    resp2 = client.post("/from_r2", files=files, headers={"x-api-key": "secret-key"})
    assert resp2.status_code == 200
    assert resp2.json()['text'] == "hello"